export interface Activity {
  id: string;
  title: string;
  scene: string;
  image?: string;
  description: string;
  bestSeason: string;
  difficulty: string;
  duration: string;
  nearby: string[];
  safetyTips: string[];
  videoUrl: string;
  reelUrl: string;
}

export const ACTIVITIES: Activity[] = [
  {
    id: "rafting",
    title: "River Rafting",
    scene: "tsomgo",
    description:
      "The Teesta and Rangit carve deep gorges below Gangtok and Melli — rapids from Grade II family floats to Grade IV white water.",
    bestSeason: "Sep–Nov & Mar–May",
    difficulty: "Moderate",
    duration: "2–4 hours",
    nearby: ["Melli Bazaar", "Kalisky", "Gangtok"],
    safetyTips: ["Always raft with a licensed operator", "Wear the helmet and life jacket at all times", "Do not raft after heavy rain", "Non-swimmers should choose the calmer stretches"],
    videoUrl: "https://www.youtube.com/results?search_query=river+rafting+teesta+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/teestariverrafting/",
  },
  {
    id: "paragliding",
    title: "Paragliding",
    scene: "ravangla",
    description:
      "Tandem flights launch from the ridgelines near Ravangla and Legship, soaring over pine forests toward the plains.",
    bestSeason: "Oct–Apr",
    difficulty: "Easy (tandem)",
    duration: "15–20 min flight",
    nearby: ["Ravangla Buddha Park", "Legship", "Namchi"],
    safetyTips: ["Choose certified pilots and operators", "Check weather windows before booking", "Dress warm — altitude is cold", "Follow all pilot briefings"],
    videoUrl: "https://www.youtube.com/results?search_query=paragliding+ravangla+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/paraglidingsikkim/",
  },
  {
    id: "yakride",
    title: "Yak Ride",
    scene: "yumthang",
    description:
      "A slow, gentle ride across the high meadows of Yumthang and above Tsomgo Lake — Sikkim's most charming way to cross a valley.",
    bestSeason: "May–Jun & Sep–Oct",
    difficulty: "Easy",
    duration: "30 min – 1 hour",
    nearby: ["Yumthang Valley", "Tsomgo Lake", "Gurudongmar"],
    safetyTips: ["Ride with an attendant; yaks can be playful", "Hold the harness firmly", "Avoid sudden movements", "Dress warmly for high altitude"],
    videoUrl: "https://www.youtube.com/results?search_query=yak+ride+sikkim+yumthang",
    reelUrl: "https://www.instagram.com/explore/tags/yakridesikkim/",
  },
  {
    id: "cablecar",
    title: "Cable Car",
    scene: "gangtok",
    description:
      "Gangtok's ropeway glides from the lower bazaar up over the rooftops — a five-minute float that turns the whole city into a diorama.",
    bestSeason: "All year",
    difficulty: "Easy",
    duration: "10 min loop",
    nearby: ["MG Marg", "Deorali", "Tashi Viewpoint"],
    safetyTips: ["Queue early on weekends", "Keep belongings secured", "Children must be accompanied", "Enjoy the view over the valley"],
    videoUrl: "https://www.youtube.com/results?search_query=gangtok+ropeway+cable+car",
    reelUrl: "https://www.instagram.com/explore/tags/gangtokropeway/",
  },
  {
    id: "monasteryvisit",
    title: "Monastery Visit",
    scene: "rumtek",
    description:
      "Walk the great halls of Rumtek, Pemayangtse, Enchey and Tashiding — where scripture, art and silence meet.",
    bestSeason: "All year; mornings best",
    difficulty: "Easy",
    duration: "Half day each",
    nearby: ["Rumtek", "Enchey", "Pemayangtse", "Tashiding"],
    safetyTips: ["Remove shoes before prayer halls", "Ask before photographing monks", "Cover shoulders and knees", "Turn prayer wheels clockwise"],
    videoUrl: "https://www.youtube.com/results?search_query=rumtek+monastery+guided+tour",
    reelUrl: "https://www.instagram.com/explore/tags/rumtekmonastery/",
  },
  {
    id: "camping",
    title: "Camping",
    scene: "lachen",
    description:
      "Tent nights under the high Himalaya — beside alpine lakes and in the valley meadows of North Sikkim.",
    bestSeason: "May–Jun & Sep–Oct",
    difficulty: "Moderate",
    duration: "1–3 nights",
    nearby: ["Lachen", "Thangu", "Gurudongmar", "Yumthang"],
    safetyTips: ["Camp only at designated sites", "Carry warm sleeping bags — nights freeze", "Keep food sealed from wildlife", "Acclimatise before high camps"],
    videoUrl: "https://www.youtube.com/results?search_query=camping+north+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/campingsikkim/",
  },
  {
    id: "photography",
    title: "Photography",
    scene: "khangchendzonga",
    description:
      "Chase golden roofs, morning mist and the great Kanchenjunga wall — Sikkim is a photographer's pilgrimage.",
    bestSeason: "Oct–Apr (clear peaks)",
    difficulty: "Easy",
    duration: "Flexible",
    nearby: ["Pelling", "Tsomgo Lake", "Gurudongmar", "Ravangla"],
    safetyTips: ["Carry spare batteries — cold drains them", "Photograph monks only with permission", "Use ND filters for waterfalls", "Respect 'no photography' shrine signs"],
    videoUrl: "https://www.youtube.com/results?search_query=sikkim+photography+tour",
    reelUrl: "https://www.instagram.com/explore/tags/sikkimphotography/",
  },
  {
    id: "naturewalk",
    title: "Nature Walk",
    scene: "khecheopalri",
    description:
      "Sacred forests, fern-lined paths and the still waters of Khecheopalri — a forest bath for the soul.",
    bestSeason: "Mar–May & Sep–Nov",
    difficulty: "Easy",
    duration: "2–4 hours",
    nearby: ["Khecheopalri Lake", "Pelling", "Yuksom"],
    safetyTips: ["Follow marked forest trails", "Carry water and light rain gear", "Do not feed the monkeys", "Hire a local guide in dense forest"],
    videoUrl: "https://www.youtube.com/results?search_query=khecheopalri+lake+nature+walk",
    reelUrl: "https://www.instagram.com/explore/tags/khecheopalri/",
  },
  {
    id: "trekking",
    title: "Mountain Trekking",
    scene: "zuluk",
    image: "/activities/trekking.jpg",
    description:
      "From the Goechala approach to the Singalila ridge, Sikkim's trails climb toward the roof of the world.",
    bestSeason: "Apr–May & Oct–Nov",
    difficulty: "Strenuous",
    duration: "5–14 days",
    nearby: ["Goechala", "Sandakphu", "Dzongri", "Yuksom"],
    safetyTips: ["Trek with a registered operator", "Acclimatise slowly above 3,000 m", "Carry a first-aid kit and AMS awareness", "Register at forest checkposts"],
    videoUrl: "https://www.youtube.com/results?search_query=sikkim+trekking+goechala",
    reelUrl: "https://www.instagram.com/explore/tags/sikkimtrekking/",
  },
  {
    id: "rockclimbing",
    title: "Rock Climbing",
    scene: "namchi",
    description:
      "Bolted crags and bouldering near Namchi and Gangtok give climbers a cool-season vertical fix.",
    bestSeason: "Oct–Apr",
    difficulty: "Moderate to Hard",
    duration: "Half day",
    nearby: ["Namchi", "Gangtok", "Rangpo"],
    safetyTips: ["Climb only with certified instructors", "Inspect anchors and bolts", "Use a helmet and belay properly", "Avoid wet rock"],
    videoUrl: "https://www.youtube.com/results?search_query=rock+climbing+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/climbingsikkim/",
  },
  {
    id: "snow",
    title: "Snow Activities",
    scene: "yumthang",
    description:
      "Snowball fights, sledding and first snow play at Tsomgo, Nathula and Yumthang when the passes whiten.",
    bestSeason: "Dec–Mar",
    difficulty: "Easy",
    duration: "Half day",
    nearby: ["Tsomgo Lake", "Nathula Pass", "Yumthang Valley"],
    safetyTips: ["Check road and permit status", "Carry warm waterproof gear", "Watch for slippery patches", "Limit time at extreme altitude"],
    videoUrl: "https://www.youtube.com/results?search_query=snowfall+tsomgo+lake+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/snowsikkim/",
  },
  {
    id: "teagarden",
    title: "Tea Garden Visit",
    scene: "barsey",
    description:
      "The Temi Tea Garden, India's only organic tea estate, terraces the hillsides above a quiet valley in South Sikkim.",
    bestSeason: "Apr–Nov",
    difficulty: "Easy",
    duration: "2–3 hours",
    nearby: ["Temi Tea Garden", "Namchi", "Ravangla"],
    safetyTips: ["Visit the factory in season", "Wear walking shoes on the terraces", "Photograph workers with permission", "Buy direct from the estate shop"],
    videoUrl: "https://www.youtube.com/results?search_query=temi+tea+garden+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/temiteagarden/",
  },
  {
    id: "hotsprings",
    title: "Hot Springs",
    scene: "tsomgo",
    description:
      "Mineral springs at Borong, Reshi and Phurchachu — warm pools where travellers soak mountain tiredness away.",
    bestSeason: "Oct–Apr",
    difficulty: "Easy",
    duration: "1–2 hours",
    nearby: ["Borong", "Reshi", "Phurchachu", "Tashiding"],
    safetyTips: ["Check water temperature before entry", "Limit soak time", "Cover up — springs are shared spaces", "Carry your own towel"],
    videoUrl: "https://www.youtube.com/results?search_query=hot+spring+sikkim+borong",
    reelUrl: "https://www.instagram.com/explore/tags/hotspringssikkim/",
  },
  {
    id: "birdwatching",
    title: "Bird Watching",
    scene: "temi",
    image: "/activities/birdwatching.jpg",
    description:
      "Over 550 bird species call Sikkim home — blood pheasants, firetails and the elusive pheasant-tailed jacana.",
    bestSeason: "Apr–Jun & Sep–Nov",
    difficulty: "Easy to Moderate",
    duration: "Half day",
    nearby: ["Khecheopalri", "Barsey", "Khangchendzonga NP", "Gangtok"],
    safetyTips: ["Start early — dawn is the bird hour", "Use quiet, neutral clothing", "Bring binoculars, not playback", "Stay on trails in sanctuaries"],
    videoUrl: "https://www.youtube.com/results?search_query=birdwatching+sikkim",
    reelUrl: "https://www.instagram.com/explore/tags/birdsofsikkim/",
  },
  {
    id: "cycling",
    title: "Cycling",
    scene: "ravangla",
    description:
      "Rolling ridgeline roads and Himalayan switchbacks make Sikkim a road-cyclist's dream — best on mountain bikes.",
    bestSeason: "Mar–May & Sep–Nov",
    difficulty: "Moderate to Strenuous",
    duration: "Half day to 3 days",
    nearby: ["Gangtok", "Ravangla", "Pelling", "Legship"],
    safetyTips: ["Use a helmet and hi-vis gear", "Descend slowly on switchbacks", "Carry spare tubes and tools", "Watch for share taxis on curves"],
    videoUrl: "https://www.youtube.com/results?search_query=cycling+sikkim+roads",
    reelUrl: "https://www.instagram.com/explore/tags/cyclingsikkim/",
  },
  {
    id: "mountainbiking",
    title: "Mountain Biking",
    scene: "zuluk",
    description:
      "Singletrack through rhododendron forests and down the switchbacks of the Old Silk Route near Zuluk.",
    bestSeason: "Sep–Nov & Mar–May",
    difficulty: "Strenuous",
    duration: "1–4 days",
    nearby: ["Zuluk", "Lachung", "Gangtok"],
    safetyTips: ["Use a full-suspension bike", "Ride with a group or guide", "Carry altitude medicine", "Plan climbs before noon"],
    videoUrl: "https://www.youtube.com/results?search_query=mountain+biking+sikkim+zuluk",
    reelUrl: "https://www.instagram.com/explore/tags/mtbsikkim/",
  },
  {
    id: "shopping",
    title: "Local Shopping",
    scene: "gangtok",
    description:
      "Carpets, thangkas, prayer wheels and hand-made paper from the craft bazaars of Gangtok and Namchi.",
    bestSeason: "All year",
    difficulty: "Easy",
    duration: "Half day",
    nearby: ["MG Marg, Gangtok", "Namchi Market", "Ravangla Bazaar"],
    safetyTips: ["Buy crafts from government emporiums", "Check export rules for antiques", "Bargain gently and politely", "Ask about the maker before buying"],
    videoUrl: "https://www.youtube.com/results?search_query=sikkim+shopping+gangtok",
    reelUrl: "https://www.instagram.com/explore/tags/sikkimshopping/",
  },
  {
    id: "foodtrail",
    title: "Food Trails",
    scene: "momos",
    description:
      "Steamers of momos, bowls of thukpa, sel roti and gundruk — a journey through Sikkim's three kitchens.",
    bestSeason: "All year",
    difficulty: "Easy",
    duration: "Half day to full day",
    nearby: ["Gangtok", "Pelling", "Namchi", "Lachung"],
    safetyTips: ["Choose busy, clean eateries", "Ask about spice levels", "Try fermented specialities with local guidance", "Drink bottled or boiled water"],
    videoUrl: "https://www.youtube.com/results?search_query=sikkim+food+street+gangtok",
    reelUrl: "https://www.instagram.com/explore/tags/sikkimfood/",
  },
  {
    id: "meditation",
    title: "Meditation Retreat",
    scene: "rumtek",
    image: "/activities/meditation.jpg",
    description:
      "Quiet days of mindfulness and guided meditation in the halls and forests of Sikkim's monasteries.",
    bestSeason: "Sep–May",
    difficulty: "Easy",
    duration: "2–7 days",
    nearby: ["Rumtek Institute", "Ralang", "Enchey", "Pelling"],
    safetyTips: ["Book residential courses in advance", "Arrive with modest dress", "Silence is part of the practice", "Respect monastic schedules"],
    videoUrl: "https://www.youtube.com/results?search_query=meditation+retreat+sikkim+monastery",
    reelUrl: "https://www.instagram.com/explore/tags/meditationsikkim/",
  },
];
